/**********************************************************************
 * Extern for hljs
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var hljs = {
  "ASM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {},
    "i": {}
  },
  "BE": {
    "b": {},
    "r": {}
  },
  "BNM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "BNR": {},
  "C": function () {},
  "CBCM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {}
  },
  "CLCM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {}
  },
  "CNM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "CNR": {},
  "CSSNM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "HCM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {}
  },
  "IR": {},
  "METHOD_GUARD": {
    "b": {},
    "r": {}
  },
  "NM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "NR": {},
  "PWM": {
    "b": {}
  },
  "QSM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {},
    "i": {}
  },
  "RM": {
    "b": {},
    "c": {},
    "cN": {},
    "e": {},
    "i": {}
  },
  "RSR": {},
  "TM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "UIR": {},
  "UTM": {
    "b": {},
    "cN": {},
    "r": {}
  },
  "configure": function () {},
  "fixMarkup": function () {},
  "getLanguage": function () {},
  "highlight": function () {},
  "highlightAuto": function () {},
  "highlightBlock": function () {},
  "inherit": function () {},
  "initHighlighting": function () {},
  "initHighlightingOnLoad": function () {},
  "listLanguages": function () {},
  "registerLanguage": function () {}
};
/**********************************************************************
 * End Generated Extern for hljs
/**********************************************************************/